import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import Loading from './Loading'
import { Button } from '@mui/material'

export default function Home() {

  //check if data is still fetching 
  const [loading, setLoading]= React.useState(false)
const Router = useRouter();

  //handleClick functiion
  const handleClick = ()=>{
    alert("Order placement successful")
    //to navigate programmatically
    //using replace instead of push will distroy the navigation history when trying to navigate to the previous page
    Router.replace('/product/100')


  }
  if(loading){
    return <Loading/>
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img
          src={
            "https://www.hungryjacks.com.au/App_Themes/HJ/assets/images/HJLogo.svg"
          }
          className="App-logo"
          alt="logo"
        />
        <Button variants="contained" color="success">
          <Link href="/tradinghours"> View Trading Hours</Link>
        </Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
